### ISSUE TITLE
missing reference and broken links in 2.4

### ISSUE THREAD

**Issue by bagder** [WICG/network-error-logging#56]
(Talking about http://www.w3.org/TR/network-error-logging/ as of right now.)

I was reading section 2.4 when I found a reference to a "block cookies flag" that I wasn't sure what its exact definition would be. I think it should be clarified inline somehow.

Looking for the definition I tried the "Queue a task" link (http://www.w3.org/html/wg/drafts/html/CR/webappapis.html#queue-a-task) as well as the "fetch" link (http://www.w3.org/html/wg/drafts/html/CR/infrastructure.html#fetch), and both 404s.

**Comment by igrigorik** [comment]
Fixed in new draft.
