### ISSUE TITLE
broken link on is-origin-trustworthy in 2.2.1.1

### ISSUE THREAD

**Issue by bagder** [WICG/network-error-logging#57]
the new and working target seems it should be `https://w3c.github.io/webappsec-secure-contexts/#is-origin-trustworthy`

**Comment by dcreager** [comment]
Update: link should now be https://www.w3.org/TR/secure-contexts/#is-origin-trustworthy

**Comment by dcreager** [comment]
cf #64

**Comment by igrigorik** [comment]
Fixed in new draft.
